### ISSUE TITLE
Getting .glb/.obj from training output

### ISSUE THREAD

**Issue by pablovela5620** [hanhung/PureCLIPNeRF#3]
Hi, appreciate you all opensourcing this! 
After running the sample training, I noticed that the outputs are rendered images. Is there a way to output the object to a mesh file like .glb/.obj?

Thanks again

**Comment by hanhung** [comment]
We currently do not have the functionality of exporting to a mesh. However, it could be be done by first exporting the density and color grids from the trained model and then feed through the marching cubes algorithm. Here are here few marching cubes implementation that might help: https://github.com/pmneila/PyMCubes, https://github.com/JustusThies/PyMarchingCubes. We will consider this functionality for future updates.

Thanks

**Comment by pablovela5620** [comment]
Understood, thanks for the response
